### ISSUE TITLE
Congratulations and feature requests

### ISSUE THREAD

**Issue by gkaissis** [geoffrich/marvel-by-year#14]
First of all, congratulations for this project, it's such a monumental improvement over searching the official site it's UNREAL. I'd like to make two suggestions/ feature requests if I may:

1. I couldn't find a way to search for a title over all the years, e.g. when I input "amazing", I want to get all the ASM issues from 1963 onward
2. It would be amazing (since you are using the API) to be able to search for titles not available on MU as well. Your website is such an improvement over the regular search that I'm sure many of us would love to use it for just searching stuff in general, not just MU. I think it'd be fine for most users if one clicks an issue and instead of getting the (beloved) Marvel viewer, one just gets an "issue not available on MU".

As a last point, a tiny suggestion: Perhaps put a "last updated on XX" with a timestamp when you last pulled the newest updates from the database. Perhaps (if it's incremental), add both a "last updated" (incremental) and a "last full update" (in case you do a full update occasionally).

Many thanks again! You could consider enabling sponsoring, I'd definitely tip you for continued work on this project.

**Comment by geoffrich** [comment]
Thank you, I'm glad you're enjoying the site! Since this is three different feature requests (of varying complexity), I split them all into separate issues to make tracking easier.

Not sure when I'll get to them, but you can follow those issues for updates 😊
